version: '3.9'
# usage:
# docker-compose up -d
# docker-compose down
services:
  cll_genie_app_dev:
    container_name: cll_genie_app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: host
      target: cll_genie_app_dev
    image: cll_genie:0.0.3_dev
    network_mode: bridge
    ports:
      - "5814:8000"
    environment:
      - PYHTONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - SCRIPT_NAME=''
    env_file:
      - .env
    restart: always
    volumes:
      - "./cll_genie:/cll_genie/cll_genie"
      - "./wsgi.py:/cll_genie/wsgi.py"
      - "./config.py:/cll_genie/config.py"
      - "./version.py:/cll_genie/version.py"
      - "/data/lymphotrack/cll_results/:/cll_genie/results/"
      - "/data/lymphotrack/cll_results_dev/:/cll_genie/results_dev/"
      - "/data/lymphotrack/results/lymphotrack_dx/:/data/lymphotrack/results/lymphotrack_dx/"
      - "/data/lymphotrack/logs:/cll_genie/logs"
    command: "python3 /cll_genie/wsgi.py"
